
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsuesntuixojkhqvpans.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzdWVzbnR1aXhvamtocXZwYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTUwMjQsImV4cCI6MjA1OTY3MTAyNH0.ha4pQnAzdNXqngce3Vmx34ZWYIe6q6KmjpmOZwk4dGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
